name: module_flutter_riverpod
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.2
  cupertino_icons: ^1.0.2
  business:
    path: business
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.4

flutter:
  uses-material-design: true